WIFI_SSID = 'Pixelator'
WIFI_PASS = 'Pixelator'
# Default IP
IP_ADDRESS = '192.168.108.39'
NETMASK = '255.255.255.0'

SLPL_PINNUM = 0
RSTH_PINNUM = 2   # W & E
STEP_PINNUM = 4   #COMMON
SLPH_PINNUM = 5   # W & E
RSTV_PINNUM = 12  # N & S
SLPV_PINNUM = 15  # N & S
ENL_PINNUM  = 18
PHL_PINNUM  = 19
MS1_PINNUM  = 22  #COMMON
MS2_PINNUM  = 23  #COMMON
MS3_PINNUM  = 25  #COMMON
DIR1_PINNUM = 26  # W & N
DIR2_PINNUM = 27  # S & E

#Common Pins: MS1, MS2, MS3, STEP
#Motor West:    SLPH, RSTH, DIR1
#Motor North:   SLPV, RSTV, DIR1
#Motor South:   SLPV, RSTV, DIR2
#Motor East:    SLPH, RSTH, DIR2